#!/bin/bash

#%include helpfile.sh autohelp.sh bashout.sh

#%include argumenting.sh cleaning.sh

set -u

#ALPACTION=$(get_main_action "$@")
#ALPOPTIONS=$(get_options_list "$@")
#ALPTERMS=$(get_all_terms "$@")
get_main_action "$@"
get_options_list "$@"
get_all_terms "$@"

if [[ -z "${ALPACKAS+x}" ]]; then
	ALPACKAS=
fi
