#!/usr/bin/env bash

set -euo pipefail

#%include help.sh

#%include autohelp.sh bincheck.sh args.sh runmain.sh out.sh
#%include warn.sh

paf:main() {
    PAF_activities=(:)
    PAF_packages=(:)
    PAF_sources=(:)
    PAF_action=search
    PAF_assume=

    paf:get_package_manager

    paf:help "$@"
    if [[ -z "$*" ]]; then
        out:warn "Nothing to do. Try --help ."
        exit 0
    fi

    paf:parse_arguments "$@"

    paf:run_activity update

    if [[ -n "${PAF_action:-}" ]]; then
        paf:warn "$PAF_action"

        # We pass "$@" in case it is needed
        #  but most actions just access ${PAF_packages[@]} directly
        "$PAF_pm:$PAF_action" "$@"
    fi

    paf:run_activity clean
}

paf:help() {
    if [[ "$*" =~ --help ]]; then
        autohelp:print help "$0"
        autohelp:print "help-${PAF_pm}" "$0"
        exit 0
    fi
}

paf:sudo() {
    if bincheck:has sudo; then
        sudo "$@"
        return "$?"
    else
        [[ "$UID" = 0 ]] || out:fail "No sudo, and you are not root"

        "$@"
    fi
}

paf:get_package_manager() {
    local drivers=(apt-get:dpkg dnf:rpm yum:rpm tazpkg: apk: zypper:rpm ) # pacman)
    local drive

    for drive in "${drivers[@]}"; do
        PAF_pm="${drive%:*}" # general package manager e.g. apt
        PAF_bpm="${drive#*:}" # base package manager e.g. dpkg

        bincheck:has "$PAF_pm" || continue
        return
    done

    out:fail "You distro is unsupported"
}

paf:add_activity() {
    PAF_activities[${#PAF_activities[@]}]="$1"
}

paf:run_activity() {
    local activity="$1"
    if [[ "${PAF_activities[*]:-}" =~ "$activity" ]]; then
        paf:warn "$activity"
        "$PAF_pm:$activity"
    fi
}

paf:parse_arguments() {
    for arg in "$@"; do
        case "$arg" in
        -w)
            paf:warn:warn-set "$@"
            exit 0
            ;;
        -u) paf:add_activity "update"
            if [[ "$PAF_action" = search ]]; then
                PAF_action=""
            fi
            ;;

        -c)
            paf:add_activity "clean"
            if [[ "$PAF_action" = search ]]; then
                PAF_action=""
            fi
            ;;

        -g*)    PAF_action="upgrade" ;;
        -i*)    PAF_action="install" ;;
        -r*)    PAF_action="remove" ;;
        -l*)    PAF_action="list" ;;
        -s*)    PAF_action="show" ;;

        -y) PAF_assume="yes" ;;
        -n) PAF_assume="no" ;;

        *)  PAF_packages[${#PAF_packages[@]}]="$arg" ;;
        esac
    done

    # blat the holders
    PAF_activities=("${PAF_activities[@]:1}")
    PAF_packages=("${PAF_packages[@]:1}")
}

#%include apt.sh dnf.sh tazpkg.sh apk.sh zypper.sh
# zypper.sh pacman.sh emerge.sh # To be implemented

runmain paf paf:main "$@"
